### PR TITLE
Feature: add the example for using HuggingFace filter extension

### PR DESCRIPTION
**Pull request by kokokuo**
## Description

Add the example about the repositories minimum dataset and query the result by using `huggingface_table_question_answering` filter.

## Additional Context
- The screenshot will be updated after https://github.com/Canner/vulcan-sql/pull/253 is released.
- Open the `huggingface` directory and put all tasks of Hugging Face demo examples under the `huggingface` directory.

### CODE REVIEW

**Comment by cyyeh** [comment]
@kokokuo 在Hugging Face Table Question Answering加上對應hugging face table question answering連結如何？
https://huggingface.co/tasks/table-question-answering

btw下面圖片是不是要更新？ 因為我們修改了餵給使用者的output，然後順便說明一下此filter會將hugging face table question answering api結果原封不動轉成json string?

其他LGTM :)

**Comment by cyyeh** [comment]
@kokokuo 我忘記補充，再麻煩加上這個demo的說明在專案根目錄readme，謝謝🙏

**Comment by cyyeh** [comment]
@kokokuo 另外建議可以直接補上huggingface extension doc url：https://vulcansql.com/docs/extensions/huggingface/overview

到時候vulcansql文件更新和這個branch同時更新？

**Comment by kokokuo** [comment]
> @kokokuo 另外建議可以直接補上huggingface extension doc url：https://vulcansql.com/docs/extensions/huggingface/overview
> 
> 到時候vulcansql文件更新和這個branch同時更新？

如果到時候連結位置不變，那麼會 examples 點擊自動呈現出來

**Comment by kokokuo** [comment]
Hi @cyyeh, 我已經根據你的建議調整了一版，請你再看看，感謝！

**Comment by cyyeh** [comment]
@kokokuo  LGTM 👍

**Pull request merged**
